/* Replace with your SQL commands */
CREATE TABLE subject_teacher_student (

    SUBJECT_ID INT REFERENCES subjects (SUBJECT_ID) NOT NULL,
    SUBJECT_NAME VARCHAR(40) REFERENCES subjects (NAME) NOT NULL,
    TEACHER_ID INT REFERENCES teachers (TEACHER_ID) NOT NULL,
    TEACHER_NAME VARCHAR(70) teachers (NAME) NOT NULL,
    STUDENT_ID INT REFERENCES students (STUDENT_ID) NOT NULL,
    STUDENT_ID VARCHAR(70) REFERENCES students (NAME) NOT NULL,
    MARK INT DEFAULT NULL
);